export const AUTHENTICATED = 'AUTHENTICATED';
export const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
export const FETCH_LABORERS = 'FETCH_LABORERS';
export const CREATE_LABORER = 'CREATE_LABORER';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
